version: "3.9"

services:

  webservice:
    container_name: mr_kar_web
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - database
    environment:
      - SECRET_KEY=verysecretKey
      - DEBUG=True
      - DB_NAME=postgres
      - DB_HOST=database
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=secretpassword
    command: make rundemo

  database:
    container_name: mr_kar_database
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=secretpassword
    volumes:
      - database_volume:/var/lib/postgresql/data

volumes:
  database_volume:

