# Generated by Django 4.0.5 on 2022-06-18 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='bio',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
