# Generated by Django 4.0.5 on 2022-06-18 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0003_jobskill_jobpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='jobskill',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='location',
            field=models.CharField(choices=[('Istanbul/Office', 'Istanbul/Office'), ('Ankara/Office', 'Ankara/Office'), ('Remote', 'Remote')], max_length=15),
        ),
    ]
