# Generated by Django 4.0.5 on 2022-06-18 13:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0004_jobpost_slug_jobskill_slug_alter_jobpost_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='added_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
