# Generated by Django 4.0.5 on 2022-06-18 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0005_jobpost_added_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpost',
            old_name='added_date',
            new_name='created_date',
        ),
    ]
