# Generated by Django 4.0.5 on 2022-06-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0006_rename_added_date_jobpost_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='job_type',
            field=models.CharField(choices=[('FT', 'Full-Time'), ('PT', 'Part-Time'), ('IS', 'Internship')], default='FT', max_length=2),
            preserve_default=False,
        ),
    ]
