# Generated by Django 4.0.5 on 2022-06-18 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0007_jobpost_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='candidates',
            field=models.ManyToManyField(related_name='job_posts', to='candidate.candidateprofile'),
        ),
    ]
