# Generated by Django 4.0.5 on 2022-06-18 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0008_jobpost_candidates'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='skills',
            field=models.ManyToManyField(related_name='job_skills', to='candidate.jobskill'),
        ),
    ]
