# Generated by Django 4.0.5 on 2022-06-18 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0009_candidateprofile_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='skills',
            field=models.ManyToManyField(related_name='candidates', to='candidate.jobskill'),
        ),
    ]
