# Generated by Django 4.0.5 on 2022-06-19 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0010_alter_candidateprofile_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
